### ISSUE TITLE
Dependabot is still complaining about node build tooling for frontend

### ISSUE THREAD

**Issue by coolaj86** [therootcompany/gitdeploy#15]
Re-opening because dependabot is still complaining:

<img width="1087" alt="Screen Shot 2021-03-06 at 11 56 50 AM" src="https://user-images.githubusercontent.com/122831/110217749-1266d500-7e73-11eb-951b-e5a020c1e863.png">

**Comment by ryanburnette** [comment]
https://github.com/therootcompany/gitdeploy/pull/16
