### ISSUE TITLE
stop a build on a failure

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/gitdeploy#6]
Would it be possible to write `deploy.sh` such that it stops and doesn't complete the build if a step in the build process fails? This would be useful if tests or steps fail so that the build shouldn't go into staging or production. Thoughts?

**Comment by coolaj86** [comment]
This should be at the top of the file:
```bash
set -u
set -e
```

And if you need to ignore a failure you can do either of these
```bash
set +e
this_will_fail_but_should_pass
set -e

this_will_fail_too || true
```

**Comment by ryanburnette** [comment]
I have

```bash
set -u
set -e
```

at the top of my `deploy.sh`, but I don't in the several individual scripts that make up my build process. That's probably the problem.

**Comment by coolaj86** [comment]
Does your version have this? That should startt the scripts in the right mode:

```bash
bash -o errexit -o nounset "${base_dir}/${GIT_REPO_ID}/deploy.sh"
```

https://github.com/therootcompany/gitdeploy/blob/master/examples/deploy.sh#L8

```bash
bash -o errexit -o nounset ".gitdeploy/deploy.sh"
```

https://github.com/therootcompany/gitdeploy/blob/master/examples/deploy.sh#L18

**Comment by ryanburnette** [comment]
No

**Comment by ryanburnette** [comment]
Correction. My main `deploy.sh` sitting next to the binary does. I'm deploying with `.gitdeploy/deploy.sh` in the repo, and that one does not have those lines.

**Comment by coolaj86** [comment]
```bash
bash -o errexit -o nounset ".gitdeploy/deploy.sh"
```

It _should_ be running the .gitdeploy with strict mode on.
