### ISSUE TITLE
/api/admin/jobs responding with expected body but unexpected 405 status

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/gitdeploy#8]
```
app@gitdeploy:~$ curl http://localhost:3010/api/admin/jobs
{"success":true,"jobs":[]}
app@gitdeploy:~$ curl http://localhost:3010/api/admin/jobs -I
HTTP/1.1 405 Method Not Allowed
Date: Fri, 30 Oct 2020 19:41:57 GMT

app@gitdeploy:~$
```

Is this the expected behavior?

**Comment by ryanburnette** [comment]
This does appear to only happen with curl, not with browser requests.

**Comment by coolaj86** [comment]
I'm guessing that HEAD (`-I`) is not supported for API requests because it's not a file.

If you use `-v` I would imagine that you would see the body and the correct status code.
